### PR TITLE
Use redux in react components

### PR DESCRIPTION
**Pull request by sylvester-wamaya**
- Add books to the initialState of the books array.
- Access books from booksSlice using useSelector.
- Implement add book button by using dispatch.
- Implement remove book by using dispatch and props.
- Fix linter errors.

### CODE REVIEW

**Comment by codecaiine** [comment]
Hi @sylvester-wamaya  I would like to recommend you always double-check the project requirement before submitting it. When You are submitting a project in your dashboard there is a 99% chance that will be under review. I noticed that right now while I'm reviewing your project, you are still pushing code, which can false my review.  Please make sure that next you complete your project and double-check to make sure that your project meets all the requirements before submitting it 😄

**Comment by codecaiine** [comment]
@sylvester-wamaya  Please note that for this time I will go back and review your project again.

**Comment by sylvester-wamaya** [comment]
> @sylvester-wamaya Please note that for this time I will go back and review your project again.

Well noted, @codecaiine I'll improve on that.

**Review by codecaiine — APPROVED** [review]
Hi @sylvester-wamaya  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good use of redux ✔️
- Adding and remove work as expected ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
